# Generated by Django 4.2 on 2024-06-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField()),
                ('weight', models.FloatField()),
                ('velocity', models.FloatField()),
                ('color', models.CharField(max_length=100)),
            ],
        ),
    ]
